### ISSUE TITLE
iOS 10.3's SDK give me error

### ISSUE THREAD

**Issue by iThanh** [theos/sdks#11]
Hi,

Thank you for your sdk files.
But when I using on theos (iOS 10.3.3) I got some errors.

`/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_fd_def.h:46:16: note: previous definition is here
typedef struct fd_set {
               ^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:12:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/time.h:75:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_fd_def.h:55:12: error: definition of 'fd_set' must be imported from module
      'MachO.dyld_images' before it is required
        return (_p->fds_bits[(unsigned long)_n/__DARWIN_NFDBITS] & ((__int32_t)(((unsigned long)1)<<((unsigned long)_n % __DARWIN_NF...
                  ^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_fd_def.h:46:16: note: previous definition is here
typedef struct fd_set {
               ^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:12:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/time.h:76:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timespec.h:30:1: error: redefinition of 'timespec'
_STRUCT_TIMESPEC
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timespec.h:29:33: note: expanded from macro '_STRUCT_TIMESPEC'
#define _STRUCT_TIMESPEC        struct timespec
                                       ^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timespec.h:30:1: note: previous definition is here
_STRUCT_TIMESPEC
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timespec.h:29:33: note: expanded from macro '_STRUCT_TIMESPEC'
#define _STRUCT_TIMESPEC        struct timespec
                                       ^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:12:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/time.h:77:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timeval.h:30:1: error: redefinition of 'timeval'
_STRUCT_TIMEVAL
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timeval.h:29:33: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timeval.h:30:1: note: previous definition is here
_STRUCT_TIMEVAL
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_types/_timeval.h:29:33: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:12:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/time.h:198:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_select.h:39:6: error: conflicting types for 'select'
int      select(int, fd_set * __restrict, fd_set * __restrict,
         ^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_select.h:39:6: note: previous declaration is here
int      select(int, fd_set * __restrict, fd_set * __restrict,
         ^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:13:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/types.h:81:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/machine/endian.h:35:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/arm/endian.h:75:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_endian.h:130:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/_OSByteOrder.h:67:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/arm/OSByteOrder.h:16:1: error: redefinition of '_OSSwapInt16'
_OSSwapInt16(
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/arm/OSByteOrder.h:16:1: note: previous definition is here
_OSSwapInt16(
^
While building module 'os' imported from /var/theos/vendor/include/_Prefix/HBLog.h:2:
In file included from <module-includes>:1:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/os/trace_base.h:13:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/types.h:81:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/machine/endian.h:35:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/arm/endian.h:75:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/sys/_endian.h:130:
In file included from /var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/_OSByteOrder.h:67:
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/arm/OSByteOrder.h:26:1: error: redefinition of '_OSSwapInt32'
_OSSwapInt32(
^
/var/theos/sdks/iPhoneOS10.3.sdk/usr/include/libkern/arm/OSByteOrder.h:26:1: note: previous definition is here
_OSSwapInt32(
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]`

**Comment by PoomSmart** [comment]
@iThanh Still an issue?

**Comment by kirb** [comment]
Closing due to lack of response, I believe this SDK should be fixed now.
