### ISSUE TITLE
asking for 11.4 full SDK

### ISSUE THREAD

**Issue by liuxuan30** [theos/sdks#12]
Hi there,

asking for 11.4 full SDK, thanks !

**Comment by DavidSkrundz** [comment]
I generated the 11.4 SDK at https://github.com/DavidSkrundz/sdks

**Comment by liuxuan30** [comment]
any chance to get it  merged?

**Comment by DavidSkrundz** [comment]
I've submitted #19

**Comment by TheAwesome98-Real** [comment]
> I generated the 11.4 SDK at https://github.com/DavidSkrundz/sdks

14 SDKs when?
