### ISSUE TITLE
Make package always fails.

### ISSUE THREAD

**Issue by TheRasPiGuy** [theos/sdks#14]
Ok, so whenever I try to build my tweak, it gives me a bunch of errors. Here is one of them:
`/home/*username*/theos/sdks/iPhoneOS9.3.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLDefines.h:8:9: fatal error: could not build module 'Darwin'`
I am using Cygwin on Windows 10.

**Comment by ltvill** [comment]
Same here. 26 errors.

**Comment by ltvill** [comment]
Why did you close it?
