### ISSUE TITLE
Preferences framework missing classes

### ISSUE THREAD

**Issue by xtm3x** [theos/sdks#2]
I found today that the Preferences PrivateFramework was missing some objc-classes in its .tbd.  I found  that _PSSpecifier and _PSViewController are missing but I am not sure how many others are missing from the file (or other files).

**Comment by mstg** [comment]
There is a known problem that machotbd duplicate deletion process deletes some symbols that actually is not a duplicate. Looking into a fix.

**Comment by r-plus** [comment]
I also found `_PSListController` is missing in 10.1.

**Comment by fecaleagle** [comment]
Yes, in the meantime, I've manually added back the missing Preferences symbols from a 9.x SDK.  I haven't run into it with any other frameworks.

**Comment by kirb** [comment]
Closing in favor of #7.
