### ISSUE TITLE
iOS 11.2 SDK not working on Windows 10

### ISSUE THREAD

**Issue by R0wDrunner** [theos/sdks#24]
I get a Bunch of errors using the 11.2 SDK, while trying to compile a Tweak that worked with the 9.2 SDK.
the errors: 
https://pastebin.com/a0ME7ANc

**Comment by kirb** [comment]
I don't believe the current version of the toolchain on Cygwin supports the iOS 11 SDK.

As you're on Windows 10 you should consider using [WSL](https://docs.microsoft.com/en-us/windows/wsl/about). The toolchain is pretty recent there.

**Comment by R0wDrunner** [comment]
> I don't believe the current version of the toolchain on Cygwin supports the iOS 11 SDK.
> 
> As you're on Windows 10 you should consider using [WSL](https://docs.microsoft.com/en-us/windows/wsl/about). The toolchain is pretty recent there.

I am now using WSL, yet I get the same errors as in Cygwin. iOS 11.2 SDK.

**Comment by kemmis** [comment]
Does anyone know if anything above 9.2 is working yet on WSL?

**Comment by kirb** [comment]
Should be fixed now with the regenerated SDKs.
