### ISSUE TITLE
sdk 11.2 give me an error, i use xcode 11.3

### ISSUE THREAD

**Issue by skfly007** [theos/sdks#32]
skflydeMBP:skflytest skfly$ make clean package
==> Cleaning…
> Making all for tweak skflytest…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
While building module 'UIKit' imported from /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/Prefix.pch:39:
While building module 'FileProvider' imported from /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSFileProviderExtension.h:14:
In file included from <module-includes>:1:
In file included from /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/FileProvider.h:8:
/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:71:12: error: attributes may not be specified on a
      category
@interface NSFileProviderExtension (NSFileProviderDomain)
           ^
While building module 'UIKit' imported from /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/Prefix.pch:39:
In file included from <module-includes>:1:
In file included from /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:64:
/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS11.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSFileProviderExtension.h:14:9: fatal error: could not build module
      'FileProvider'
#import <FileProvider/NSFileProviderExtension.h>
 ~~~~~~~^
In file included from <built-in>:1:
/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/Prefix.pch:39:9: fatal error: could not build module 'UIKit'
#import <UIKit/UIKit.h>
 ~~~~~~~^
3 errors generated.
make[3]: *** [/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/skflytest/.theos/obj/debug/arm64/Tweak.x.b7b7c1eb.o] Error 1
rm /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/skflytest/.theos/obj/debug/arm64/Tweak.x.m
make[2]: *** [/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/skflytest/.theos/obj/debug/arm64/skflytest.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [skflytest.all.tweak.variables] Error 2

**Comment by kirb** [comment]
Should be fixed now with the regenerated SDKs.
