### ISSUE TITLE
sdk 10.3 give me an warning. i use xcode 11.3

### ISSUE THREAD

**Issue by skfly007** [theos/sdks#33]
skflydeMBP:skflytest skfly$ make clean package
==> Cleaning…
> Making all for tweak skflytest…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Linking tweak skflytest (arm64)…
ld: warning: OS version (6.0.0) too small, changing to 7.0.0
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/libobjc.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/libSystem.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/libc++.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//Metal.framework/Metal.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CoreVideo.framework/CoreVideo.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CoreImage.framework/CoreImage.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//Security.framework/Security.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CFNetwork.framework/CFNetwork.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CoreGraphics.framework/CoreGraphics.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//OpenGLES.framework/OpenGLES.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//QuartzCore.framework/QuartzCore.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//CoreText.framework/CoreText.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/Frameworks//UIKit.framework/UIKit.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libcache.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libcommonCrypto.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libcompiler_rt.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libcopyfile.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libcorecrypto.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libdispatch.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libdyld.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libkeymgr.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/liblaunch.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libmacho.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libremovefile.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_asl.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_blocks.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_c.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_configuration.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_containermanager.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_coreservices.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_coretls.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_dnssd.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_info.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_kernel.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_m.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_malloc.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_network.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_networkextension.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_notify.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_platform.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_pthread.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_sandbox.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_symptoms.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libsystem_trace.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libunwind.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libvminterpose.tbd) built for iOS Simulator
ld: warning: building for iOS, but linking in .tbd file (/Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/theos/theos_master_20200110/sdks/iPhoneOS10.3.sdk/usr/lib/system/libxpc.tbd) built for iOS Simulator
==> Generating debug symbols for skflytest…
rm /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/skflytest/.theos/obj/debug/arm64/Tweak.x.m
==> Merging tweak skflytest…
==> Signing skflytest…
> Making stage for tweak skflytest…
dm.pl: building package `com.yourcompany.skflytest:iphoneos-arm' in `./packages/com.yourcompany.skflytest_0.0.1-23+debug_iphoneos-arm.deb'

**Comment by kirb** [comment]
Should be fixed now with the regenerated SDKs.
