### ISSUE TITLE
i want to generate sdk from dyld_shared_cache_arm64 , but it report following error

### ISSUE THREAD

**Issue by skfly007** [theos/sdks#34]
skflydeMBP:sdks skfly$ ./create_patched_sdk.sh ./dyld_shared_cache_arm64 ./tmp/ - - /Volumes/DISK_02_USER_DATA/Users/skfly/Desktop/__SKFLY/AI/tbd_v2.1/tbd.dms -
./create_patched_sdk.sh: line 92: realpath: command not found

**Comment by hnsxcxwpf2** [comment]
and then i use tbd command , but it do not generate headers .

**Comment by inoahdev** [comment]
@hnsxcxwpf2 The script is being updated right now, and a far more reliable python script is in the works.

On using tbd, what was your commander and what errors/output/unexpected results did you find?

**Comment by hnsxcxwpf2** [comment]
skflydeMBP:_BAK skfly$ ~/Desktop/__SKFLY/AI/tbd_v2.1/tbd.dms -p ./dyld_shared_cache_arm64 -o ./tmp/
skflydeMBP:_BAK skfly$ 

it generate *.tbd files , but has no *.framwork/Headers/*.h files.

**Comment by inoahdev** [comment]
@hnsxcxwpf2 The tbd command only generates .tbd files. The header files are copied over from the Xcode SDK in the script file

**Comment by kirb** [comment]
How did you go with this @skfly007 / @inoahdev?

**Comment by leptos-null** [comment]
Checking in on this thread (it looks like kirb also checked in over a year ago). Is there still an issue? 

I plan to close this issue next week if there is no further activity.
