### ISSUE TITLE
.xm files fail to build with 14.5 sdk while .x && .m ones don't with the same code

### ISSUE THREAD

**Issue by Luki120** [theos/sdks#49]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create two projects, TestOne and TestTwo
2. The only modifications needed are specifying the iOS 14.5 sdk in the `TARGET` line for both projects, and then renaming Tweak.x to Tweak.xm for TestTwo
3. Add a single line to both `@import UIKit;`

What happens?

The tweak with the .x or .m extension will build successfully while the one with `.xm` will throw either 7 errors if nothing is added, or 52 errors when importing UIKit.

What were you expecting to happen?

To compile successfully with the iOS 14.5 sdk (grabbed from this repository) regardless the file extension

Any logs, error output, etc?

The 7 errors with an empty Tweak.xm file -> https://gist.github.com/Luki120/447b88b4e2712ed26199c0e922b56ae4

The 52 errors when importing UIKit -> https://gist.github.com/Luki120/082628323b665d36670bd38a15f40a02

Any other comments?

The makefile TARGET line looks like this `TARGET := iphone:clang:14.5:7.0`, also I'm running the latest version of theos according to the last commit on gh. Just importing Foundation by itself throws 15 errors as well, similar to the other ones

What versions of software are you using?

**Operating System:** Ubuntu 21.04 x86_64

**Toolchain Version:** Swift 5.3.2 from CRKatri

**SDK Version:** 14.5

**Comment by Zemyoro** [comment]
I too am experiencing this issue.

Operating System: Ubuntu 20.04.3 x86_64 (WSL)
Toolchain Version: Swift 5.3.2 from CRKatri
SDK Version: 14.5

**Comment by uroboro** [comment]
Fixed with https://github.com/theos/sdks/commit/fd931ca723ee46994ad9f73c2f0929d1ab9732ca

**Comment by Luki120** [comment]
This never got fixed, having the same errors..

**Comment by Luki120** [comment]
It seems I hadn't the latest commit on my setup, tho I remember having updated it, anyways nvm
