### ISSUE TITLE
iOS 11 betas please..

### ISSUE THREAD

**Issue by oscarbg** [theos/sdks#5]
Want to see how PrivateFrameworks have been changed..

**Comment by kirb** [comment]
Only going to provide notable releases at this point (hence why we don't have 10.2 or 10.3). Betas are too numerous and as far as I remember still under nondisclosure (discussion is allowed, sharing outside the developer program isn't). 

I'd say the best solution is to manually dump headers using RuntimeBrowser; it's better suited for diffing anyway.
