### ISSUE TITLE
how to use create_patched_sdk.sh?

### ISSUE THREAD

**Issue by qiaoyun680** [theos/sdks#60]
how to use create_patched_sdk.sh to patch sdk?

**Comment by leptos-null** [comment]
May you explain what you tried and what you expected? 
You should just be able to run `sdks/create_patched_sdk.sh` and it will run with a set a default parameters.
The parameters are described here: <https://github.com/theos/sdks/blob/bb425abf3acae8eac328b828628b82df544d2774/create_patched_sdk.sh#L4-L5>

**Comment by L1ghtmann** [comment]
Closing due to lack of response. Feel free to reopen if you still have questions.
