### ISSUE TITLE
Fix and add updated SDKs

### ISSUE THREAD

**Issue by kirb** [theos/sdks#7]
* Re-generate 9.3 with inoahdev’s `tbd`
* Replace broken 10.1 with working 10.3
* Add 11.2

**Comment by nullpixel** [comment]
this would be really helpful

**Comment by esterTion** [comment]
I've actually finished dumping iOS 10.3, and its waiting in PR to be merged. 
Apple's "full OTA" really makes things so easy to play with.

**Comment by kirb** [comment]
Done as of 226bae0.
