### ISSUE TITLE
Error importing Foundation/Foundation.h - Linux with iOS 16.5 sdk

### ISSUE THREAD

**Issue by slayy2357** [theos/sdks#70]
What are the steps to reproduce this issue?
-------------------------------------------
1. #import <Foundation/Foundation.h>
2. make

What happens?
 - Error when building

What were you expecting to happen?
Dylib build

Any logs, error output, etc?
[Gist error link](https://gist.github.com/slayy2357/b8d0a3fb78a16d66adcc5356ed7cc41d)

What versions of software are you using?
----------------------------------------
**Operating System:** Linux (debian)

**Toolchain Version:** I don't know

**SDK Version:** 16.5

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this! 

To quote a message from the Theos discord: 

Apologies, the current swift toolchain is outdated. You can install an up-to-date one by running 

```
rm -rf $THEOS/toolchain/*
curl -sL https://github.com/kabiroberai/swift-toolchain-linux/releases/download/v2.3.0/swift-5.8-ubuntu20.04.tar.xz | tar -xJvf - -C $THEOS/toolchain/
```

This should solve your issue.

**Comment by slayy2357** [comment]
You are a life saver, closing (thanks :)
